name: 'CalVer Tag Create and Push'
description: 'Creates a unique version tag and pushes it'
outputs:
  version:
    description: Generated version
    value: ${{ steps.tag-and-push.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: tag-and-push
      shell: bash
      run: sh "${{ github.action_path }}/tag-and-push.sh"
